import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { getAllFilesMetadata } from '../lib/mdx'

export default function Home({ posts }) {
  return (
    // <div className={styles.container}>
    <div>
      <Head>
        <title>Blog JAMStack</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="p-6 max-w-sm mx-auto bg-white rounded-xl shadow-md flex items-center space-x-4">
        <div className="flex-shrink-0">
          <Image className="h-60 w-60" src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </div>
        <div>
          <div className="text-xl font-medium text-black">ChitChat</div>
          <p className="text-gray-500">You have a new message!</p>
        </div>
      </div>

      {/* <main className={styles.main}> */}
      <main>
        <h1>
          Mi Blog con JAMStack
        </h1>

        <p>
          Get started by editing{' '}
          <code>pages/index.js</code>
        </p>

        <div>
          { posts.map(post => (
            <Link key={post.slug} href={`/${post.slug}`}>
              <a>
                <h2>{post.title} &rarr;</h2>
                <p>{post.date}</p>
              </a>
            </Link>
          )) }
        </div>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )

}


export async function getStaticProps() {

  const posts = await getAllFilesMetadata();

  console.log('Mis posts :: ', posts);

  return {
    props: { posts }
  };

}
